SAMPLES: [
          "ERR3813867",
          "ERR3813868"
         ]
# SAMPLEGROUP:
#   ChIP: "ERR3813867"
#   control: "ERR3813868"
THREADS: 35
MEMORY: "250g"
FILTER:
  fastqc:
      adapters: "data/adapter_list.txt"
  cutadapt:
      read1: AGATCGGAAGAG # ILLUMINA UNIVERSAL ADAPTER
      read2: AGATCGGAAGAG # ILLUMINA UNIVERSAL ADAPTER
      minimum-overlap: 3 # -O (default: 3)
# NOTE: reference genome-specific mapping parameters
MAPPING:
      # alignments: 10 # "In -k <N> mode, Bowtie 2 searches for up to N distinct, valid alignments for each read"
      reference: "/home/nison/work/refgenome/TAIR10/bowtie2_index/tair10"
      MAPQmaxi: 10 # -q
      sortMemory: "5G"
COVERAGE:
      normalizeUsing: "BPM"
      ignoreForNormalization: "ChrC ChrM" # Reference genome-specific parameter
      extendReads: 150
      binSize: 1
      genomeBinSize: 10000
      genomeBinName: "10kb"

METAPROFILE:
      region: "/home/nison/work/various_regions/araport11_protein-coding-genes_chr15.bed"
      binSize: 10
      upstream: 2000
      downstream: 2000

# NEBNext adapter and universal primer for Illumina:
# https://international.neb.com/-/media/catalog/datacards-or-manuals/manuale7335.pdf
# https://www.biostars.org/p/149301/
# https://cutadapt.readthedocs.io/en/stable/guide.html#illumina-truseq
# http://bioinformatics.cvr.ac.uk/blog/illumina-adapter-and-primer-sequences/
# TruSeq adapters:
# http://emea.support.illumina.com/bulletins/2016/12/what-sequences-do-i-use-for-adapter-trimming.html
